switch to modernized mods

diff --git a/etc/game-install-ENLIVEN b/etc/game-install-ENLIVEN
--- a/etc/game-install-ENLIVEN
+++ b/etc/game-install-ENLIVEN
@@ -21,31 +21,7 @@
 sudo echo "starting ENLIVEN installer script..."
 
 
-## this space was intentinally left blank
-
-
-if [ ! -f "`command -v minetestmapper`" ]; then
-  if [ -f "`command -v apt`" ]; then
-    sudo apt -y install libgd-dev libsqlite3-dev libleveldb-dev libhiredis-dev libpq-dev
-  else
-    if [ -f "`command -v pacman`" ]; then
-      pacman -Syyu --noconfirm gd sqlite leveldb hiredis postgresql #postgresql-libs
-    fi
-  fi
-  cd ~/Downloads
-  if [ -d minetestmapper ]; then
-    rm -Rf minetestmapper
-  fi
-  git clone https://github.com/minetest/minetestmapper.git
-  cd minetestmapper
-  cmake . -DENABLE_LEVELDB=1
-  make -j2
-  if [ -f minetestmapper ]; then
-    sudo cp -f minetestmapper /usr/local/bin/
-  else
-    echo "FAILED to compile minetestmapper--python version will be used"
-  fi
-fi
+## this space was intentionally left blank
 
 
 
@@ -149,6 +125,7 @@ else
     echo "You must have pasted this into terminal, so assuming MT_MYWORLD_NAME:"
     echo "  $MT_MYWORLD_NAME"
   else
+    ls $MT_WORLDS_DIR
     read -p "Please enter a world [blank for $MT_DEFAULT_WORLD_NAME]: " MT_MYWORLD_NAME
     if [ -z "$MT_MYWORLD_NAME" ]; then
       MT_MYWORLD_NAME="$MT_DEFAULT_WORLD_NAME"
@@ -268,7 +245,7 @@ add_git_mod()
     sleep 1
     exit 1
   else
-    echo "  added as $MTMOD_DEST_PATH"
+    echo "  [ + ] added as $MTMOD_DEST_PATH"
   fi
 }
 
@@ -279,21 +256,23 @@ remove_mod()
   MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
   if [ -d "$MTMOD_DEST_PATH" ]; then
     sudo rm -Rf "$MTMOD_DEST_PATH"
-  fi
-  if [ -d "$MTMOD_DEST_PATH" ]; then
-    echo "  ERROR in remove_mod: failed to remove $MTMOD_DEST_PATH, so cannot continue." > $err_txt
-    cat $err_txt
-    echo "  press Ctrl C to cancel ENLIVEN install or this terminal will close..."
-    sleep 1
-    echo " 3..."
-    sleep 1
-    echo " 2..."
-    sleep 1
-    echo " 1..."
-    sleep 1
-    exit 1
+    if [ -d "$MTMOD_DEST_PATH" ]; then
+      echo "  ERROR in remove_mod: failed to remove $MTMOD_DEST_PATH, so cannot continue." > $err_txt
+      cat $err_txt
+      echo "  press Ctrl C to cancel ENLIVEN install or this terminal will close..."
+      sleep 1
+      echo " 3..."
+      sleep 1
+      echo " 2..."
+      sleep 1
+      echo " 1..."
+      sleep 1
+      exit 1
+    else
+      echo "  [ - ] removed $MTMOD_DEST_PATH"
+    fi
   else
-    echo "  removed $MTMOD_DEST_PATH"
+    echo "  [ - ] already not present: $MTMOD_DEST_PATH"
   fi
 }
 
@@ -306,8 +285,33 @@ remove_mod()
 
 
 
-## this space was intentinally left blank
+## this space was intentionally left blank
 
+
+
+
+if [ ! -f "`command -v minetestmapper`" ]; then
+  if [ -f "`command -v apt`" ]; then
+    sudo apt -y install libgd-dev libsqlite3-dev libleveldb-dev libhiredis-dev libpq-dev
+  else
+    if [ -f "`command -v pacman`" ]; then
+      pacman -Syyu --noconfirm gd sqlite leveldb hiredis postgresql #postgresql-libs
+    fi
+  fi
+  cd ~/Downloads
+  if [ -d minetestmapper ]; then
+    rm -Rf minetestmapper
+  fi
+  git clone https://github.com/minetest/minetestmapper.git
+  cd minetestmapper
+  cmake . -DENABLE_LEVELDB=1
+  make -j2
+  if [ -f minetestmapper ]; then
+    sudo cp -f minetestmapper /usr/local/bin/
+  else
+    echo "FAILED to compile minetestmapper--python version will be used"
+  fi
+fi
 
 if [ -d /tmp/local_mts_user ]; then
   # handle paranoia about directory with similar name
@@ -387,7 +391,7 @@ if [ -d "$USR_SHARE_MINETEST/games/minetest" ]; then
   # Arch linux
   mtgame_name="minetest"
 fi
-sudo cp -R $USR_SHARE_MINETEST/games/$mtgame_name/* "$MT_MYGAME_DIR/"
+sudo cp -Rf $USR_SHARE_MINETEST/games/$mtgame_name/* "$MT_MYGAME_DIR/"
 
 #wget https://github.com/BlockMen/cme/releases/download/v2.3/cme-2_3-BlockMen.zip
 #unzip cme-2_3-BlockMen.zip
@@ -403,6 +407,12 @@ add_git_mod mobs_monster mobs_monster https://github.com/tenplus1/mobs_monster.g
 echo "load_mod_mobs_monster = true" >> "$WORLD_MT_PATH"
 add_git_mod mobs_animal mobs_animal https://github.com/tenplus1/mobs_animal.git
 echo "load_mod_mobs_animal = true" >> "$WORLD_MT_PATH"
+
+add_git_mod sounding_line sounding_line https://github.com/minetest-mods/sounding_line.git
+add_git_mod lightning lightning https://github.com/minetest-mods/lightning.git
+add_git_mod mywalls mywalls https://github.com/minetest-mods/mywalls.git
+add_git_mod mymasonhammer mymasonhammer https://github.com/minetest-mods/mymasonhammer.git
+add_git_mod ts_furniture ts_furniture https://github.com/minetest-mods/ts_furniture.git
 
 # forum_url="https://forum.minetest.net/viewtopic.php?f=11&t=9376"
 # author="tenplus1"
@@ -433,7 +443,7 @@ echo "motd = \"Actions and chat messages are logged. Use inventory to see recipe
 echo "disallow_empty_passwords = true" >> "$WRITEABLE_MINETEST_CONF"
 echo "secure.trusted_mods = advanced_npc" >> "$WRITEABLE_MINETEST_CONF"
 echo "server_dedicated = false" >> "$WRITEABLE_MINETEST_CONF"
-echo "hudbars_bar_type = statbar_modern" >> "$WRITEABLE_MINETEST_CONF"
+echo "hudbars_bar_type = statbar_modern" >> "$WRITEABLE_MINETEST_CONF"  #TODO: remove this after fully deprecated
 sudo mv -f $HOME/minetest.conf "$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf"
 echo "load_mod_protector = true" >> "$WORLD_MT_PATH"
 
@@ -496,6 +506,8 @@ sudo mv -f LICENSE "$MTMOD_DEST_PATH/"
 cd ..
 rmdir "$MTMOD_UNZ_NAME"
 
+remove_mod sprint
+remove_mod hudbars
 add_git_mod hbsprint hbsprint https://github.com/minetest-mods/hbsprint.git
 add_git_mod armor_monoid armor_monoid https://github.com/minetest-mods/armor_monoid.git
 
@@ -562,11 +574,12 @@ remove_mod helicopter
 add_git_mod biome_lib biome_lib https://github.com/minetest-mods/biome_lib.git
 add_git_mod moretrees moretrees https://github.com/minetest-mods/moretrees.git
 add_git_mod 3d_armor minetest-3d_armor https://github.com/stujones11/minetest-3d_armor.git
-#TODO 0.5 version??: https://github.com/stujones11/minetest-3d_armor/archive/MT_0.5.0-dev.zip
+#TODO 0.5 version??:
 # Git 1.7.10 need `--single-branch` option to prevent getting all branches (see https://stackoverflow.com/questions/1911109/how-to-clone-a-specific-git-branch)
 #git clone -b MT_0.5.0-dev --single-branch https://git@github.com/stujones11/minetest-3d_armor.git
 #see also 0.5 branch https://github.com/stujones11/minetest-3d_armor/tree/MT_0.5.0-dev
 #"stable" version is at https://github.com/stujones11/minetest-3d_armor/archive/version-0.4.11.zip
+#add_zip_mod 3d_armor minetest-3d_armor-MT_0.5.0-dev https://github.com/stujones11/minetest-3d_armor/archive/MT_0.5.0-dev.zip
 
 #mv minetest-3d_armor-master minetest-3d_armor_MODPACK
 #sudo mv minetest-3d_armor_MODPACK/wieldview $MT_MYGAME_MODS_PATH/wieldview
@@ -576,9 +589,9 @@ add_git_mod 3d_armor minetest-3d_armor https://github.com/stujones11/minetest-3d
 echo "load_mod_3d_armor = true" >> "$WORLD_MT_PATH"
 #echo "load_mod_shields = true" >> "$WORLD_MT_PATH"
 #echo "load_mod_technic_armor = false" >> "$WORLD_MT_PATH"
-
-add_git_mod caverealms minetest-caverealms https://github.com/HeroOfTheWinds/minetest-caverealms
-
+#add_git_mod caverealms minetest-caverealms https://github.com/HeroOfTheWinds/minetest-caverealms
+echo "Installing FaceDeer's v7-biome-integrated fork of HeroOfTheWinds' caverealms"
+add_git_mod caverealms minetest-caverealms https://github.com/FaceDeer/minetest-caverealms.git
 #if [ -f "master.zip" ]; then
   #rm master.zip
 #fi
@@ -670,59 +683,84 @@ add_zip_mod metatools minetest-mod-metatools-master https://github.com/expertmm/
 #requires mobs redo
 add_zip_mod mobs_sky mobs_sky-master https://github.com/blert2112/mobs_sky/archive/master.zip
 
-# forum_url: https://forum.minetest.net/viewtopic.php?f=11&t=13857
-# description:
-# * REPLACES pyramids.
-# * Works with mobs_redo and creatures.
-# * optionally makes use of fire (in minetest_game; only uses fire:flint_and_steel), mobs, creatures, bones, xpanes (now part of minetest_game)
-# * only RECIPES require fake_fire and xpanes
-# * NOW (2017-2018) IS A MODPACK: formerly was a mod named spawners, now is a modpack containing:
-#   * spawners_env: appears in Dungeons and Temples (the pink stone ones); spawns hostile mobs; has small chance of spawning a spawner
-#   * spawners_mobs: spawns non-hostile mobs
-#   * spawners_ores: spawns ores
-#add_zip_mod spawners minetest_gamers-spawners-* https://bitbucket.org/minetest_gamers/spawners/get/master.zip
-add_git_mod spawners spawners https://bitbucket.org/minetest_gamers/spawners.git
-MTMOD_DEST_NAME=spawners/spawners_ores
-MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
-if [ -d "$MTMOD_DEST_PATH" ]; then
-  echo "removing $MTMOD_DEST_NAME..."
-  sudo rm -Rf "$MTMOD_DEST_PATH"
+spawners_enable="false"
+if [ "$spawners_enable" = "true" ]; then
+  # forum_url: https://forum.minetest.net/viewtopic.php?f=11&t=13857
+    # description:
+    # * REPLACES pyramids.
+    # * Works with mobs_redo and creatures.
+    # * optionally makes use of fire (in minetest_game; only uses fire:flint_and_steel), mobs, creatures, bones, xpanes (now part of minetest_game)
+    # * only RECIPES require fake_fire and xpanes
+    # * NOW (2017-2018) IS A MODPACK: formerly was a mod named spawners, now is a modpack containing:
+    #   * spawners_env: appears in Dungeons and Temples (the pink stone ones); spawns hostile mobs; has small chance of spawning a spawner
+    #   * spawners_mobs: spawns non-hostile mobs
+    #   * spawners_ores: spawns ores
+    #add_zip_mod spawners minetest_gamers-spawners-* https://bitbucket.org/minetest_gamers/spawners/get/master.zip
+    add_git_mod spawners spawners https://bitbucket.org/minetest_gamers/spawners.git
+    MTMOD_DEST_NAME=spawners/spawners_ores
+    MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
+    if [ -d "$MTMOD_DEST_PATH" ]; then
+      echo "removing $MTMOD_DEST_NAME..."
+      sudo rm -Rf "$MTMOD_DEST_PATH"
+    else
+      echo "ERROR: could not find $MTMOD_DEST_PATH for removal, so cancelling ENLIVEN install"
+      echo "  press Ctrl C to cancel ENLIVEN install or this terminal will close..."
+      sleep 1
+      echo " 3..."
+      sleep 1
+      echo " 2..."
+      sleep 1
+      echo " 1..."
+      sleep 1
+      exit 1
+    fi
+    if [ -d "$MTMOD_DEST_PATH" ]; then
+      echo "ERROR: could not remove $MTMOD_DEST_PATH for removal, so cancelling ENLIVEN install"
+      echo "  press Ctrl C to cancel ENLIVEN install or this terminal will close..."
+      sleep 1
+      echo " 3..."
+      sleep 1
+      echo " 2..."
+      sleep 1
+      echo " 1..."
+      sleep 1
+      exit 1
+    fi
+
+    #defaults are:
+    #SPAWN_PYRAMIDS = false
+    #SPAWNERS_GENERATE = true
+    #CHESTS_GENERATE = false
+    MTMOD_DEST_NAME=spawners/spawners_env
+    MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
+    echo "SPAWN_PYRAMIDS = true" > settings.txt
+    echo "SPAWNERS_GENERATE = true" >> settings.txt
+    echo "CHESTS_GENERATE = false" >> settings.txt
+    sudo mv settings.txt "$MTMOD_DEST_PATH/"  # formerly $MT_MYGAME_MODS_PATH/spawners/
+    echo "NOTE: in spawners, only SPAWNERS_GENERATE or CHESTS_GENERATE, not both (SPAWNERS_GENERATE overrides) spawn in world for now. See thread for updated info: https://forum.minetest.net/viewtopic.php?f=11&t=13857&start=25"
+    echo "see also expertmm's game-install-enliven-testing-SPAWNERS_BOTH_DEBUG.txt"
+
+    # NOTE: tsm_chests_dungeon supercedes dungeon_loot:
+    if [ -d "$MT_MYGAME_MODS_PATH/dungeon_loot" ]; then
+      echo "WARNING: tsm_chests_dungeon may not be compatible with dungeon_loot"
+      echo "press Ctrl C to cancel installing ENLIVEN"
+      sleep 2
+      echo "4..."
+      sleep 1
+      echo "3..."
+      sleep 1
+      echo "2..."
+      sleep 1
+      echo "1..."
+      sleep 1
+    fi
+    add_git_mod tsm_chests_dungeon minetest_tsm_chests_dungeon http://repo.or.cz/minetest_tsm_chests_dungeon.git
 else
-  echo "ERROR: could not find $MTMOD_DEST_PATH for removal, so cancelling ENLIVEN install"
-  echo "  press Ctrl C to cancel ENLIVEN install or this terminal will close..."
-  sleep 1
-  echo " 3..."
-  sleep 1
-  echo " 2..."
-  sleep 1
-  echo " 1..."
-  sleep 1
-  exit 1
+  remove_mod tsm_chests_dungeon
+  remove_mod spawners
+  add_git_mod tsm_pyramids tsm_pyramids http://repo.or.cz/minetest_pyramids/tsm_pyramids.git
+  add_git_mod loot loot https://github.com/minetest-mods/loot.git
 fi
-if [ -d "$MTMOD_DEST_PATH" ]; then
-  echo "ERROR: could not remove $MTMOD_DEST_PATH for removal, so cancelling ENLIVEN install"
-  echo "  press Ctrl C to cancel ENLIVEN install or this terminal will close..."
-  sleep 1
-  echo " 3..."
-  sleep 1
-  echo " 2..."
-  sleep 1
-  echo " 1..."
-  sleep 1
-  exit 1
-fi
-#defaults are:
-#SPAWN_PYRAMIDS = false
-#SPAWNERS_GENERATE = true
-#CHESTS_GENERATE = false
-MTMOD_DEST_NAME=spawners/spawners_env
-MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
-echo "SPAWN_PYRAMIDS = true" > settings.txt
-echo "SPAWNERS_GENERATE = true" >> settings.txt
-echo "CHESTS_GENERATE = true" >> settings.txt
-sudo mv settings.txt "$MTMOD_DEST_PATH/"  # formerly $MT_MYGAME_MODS_PATH/spawners/
-echo "NOTE: in spawners, only SPAWNERS_GENERATE or CHESTS_GENERATE, not both (SPAWNERS_GENERATE overrides) spawn in world for now. See thread for updated info: https://forum.minetest.net/viewtopic.php?f=11&t=13857&start=25"
-echo "see also expertmm's game-install-enliven-testing-SPAWNERS_BOTH_DEBUG.txt"
 
 # forum_url: https://forum.minetest.net/viewtopic.php?t=12189
 # description: Adds animations to the players' head
@@ -784,8 +822,14 @@ add_zip_mod signs_lib signs_lib-master https://github.com/minetest-mods/signs_li
 #  exit 1
 #fi
 
-add_git_mod farming farming https://github.com/tenplus1/farming.git
+#add_git_mod farming farming https://github.com/tenplus1/farming.git
+remove_mod farming
+sudo cp -R $USR_SHARE_MINETEST/games/$mtgame_name/farming $MT_MYGAME_MODS_PATH/
+cp -Rf asdf
 
+add_git_mod vote vote https://github.com/minetest-mods/vote.git
+add_git_mod stamina stamina https://github.com/minetest-mods/stamina
+add_git_mod crops crops https://github.com/minetest-mods/crops
 # forum_url="https://forum.minetest.net/viewtopic.php?f=11&t=10423"
 # Wuzzy's slimenodes mod (only available via /give command).
 # web view: http://repo.or.cz/w/minetest_slimenodes.git
@@ -803,21 +847,6 @@ add_git_mod slimenodes slimenodes https://github.com/expertmm/slimenodes.git
 #fixed version with correct dye list for 0.4.16 (submitted pull request to ClockGen 2018-02-08):
 add_git_mod trmp_minetest_game trmp_minetest_game https://github.com/expertmm/trmp_minetest_game.git
 
-# NOTE: tsm_chests_dungeon supercedes dungeon_loot:
-if [ -d "$MT_MYGAME_MODS_PATH/dungeon_loot" ]; then
-  echo "WARNING: tsm_chests_dungeon may not be compatible with dungeon_loot"
-  echo "press Ctrl C to cancel installing ENLIVEN"
-  sleep 4
-  echo "4..."
-  sleep 1
-  echo "3..."
-  sleep 1
-  echo "2..."
-  sleep 1
-  echo "1..."
-  sleep 1
-fi
-add_git_mod tsm_chests_dungeon minetest_tsm_chests_dungeon http://repo.or.cz/minetest_tsm_chests_dungeon.git
 
 # NOTE: a skin database is at http://minetest.fensta.bplaced.net/
 # bell07's 2016 (FORK of Krock's fork of dmonty's) u_skins (u_skins is a skin GUI that works with unified_inventory, whereas other skin GUIs often use inventory++)
