working on automatic patching

diff --git a/etc/change_hardcoded_world_name_first/game-install-ENLIVEN b/etc/change_hardcoded_world_name_first/game-install-ENLIVEN
--- a/etc/change_hardcoded_world_name_first/game-install-ENLIVEN
+++ b/etc/change_hardcoded_world_name_first/game-install-ENLIVEN
@@ -10,23 +10,40 @@
 
 
 # * Git version uses /home/*/minetest/games and /usr/local/share/minetest/games but the latter is used for minetestserver (minetest-server package)
-# Known Issues:
-Uberi=`ls /usr/share/minetest/games/ENLIVEN/mods/worldedit | grep Uberi`
-if [ ! -z "$Uberi" ]; then
-  # /usr/share/minetest/games/ENLIVEN/mods/worldedit/Uberi-Minetest-WorldEdit-3322ef9
-  rm -Rf /usr/share/minetest/games/ENLIVEN/mods/worldedit
-fi
-if [ -d /usr/share/minetest/games/ENLIVEN/mods/mesecons/mesecons-master ]; then
-  rm -Rf /usr/share/minetest/games/ENLIVEN/mods/mesecons
-fi
+
 
 # (Ubuntu 14.04 Trusty Tahr Server) folders were found using:
 # cd /
 # sudo find -name 'worlds' (worlds folder is in $HOME/.minetest)
 # sudo find -name 'minimal' (stable build [such as 0.4.9 games folder is /usr/share/games/minetest/games, but git version games folder is /usr/local/share/minetest/games)
 
-sudo echo "cached password."
-# NOTE: minetest mods are ALWAYS ONLY installed on server
+# Absolute path to this script, e.g. /home/user/bin/foo.sh
+SCRIPT=$(readlink -f "$0")
+# Absolute path this script is in, thus /home/user/bin
+SCRIPTPATH=$(dirname "$SCRIPT")
+REPO_PATH=$(dirname "$SCRIPTPATH")
+
+#endregion paste this part into terminal to get some great environment variables
+
+PATCHES_PATH="$REPO_PATH/patches"
+
+if [ ! -d "$PATCHES_PATH" ]; then
+  # maybe moved somewhere or this code was pasted
+  PATCHES_PATH=$HOME/GitHub/EnlivenMinetest/patches
+fi
+if [ ! -d "$PATCHES_PATH" ]; then
+  # maybe running from root of repo
+  PATCHES_PATH="patches"
+fi
+if [ ! -d "$PATCHES_PATH" ]; then
+  # should work if ran from folder where exists
+  PATCHES_PATH="../patches"
+fi
+if [ ! -d "$PATCHES_PATH" ]; then
+  echo "ERROR: could not find patches such as in $PATCHES_PATH"
+  exit 1
+fi
+# NOTE: minetest mods (other than 0.4.16 client-side mods) are ALWAYS ONLY installed on server, unless you need them for singleplayer
 mtgame_name="minetest_game"
 USR_SHARE_MINETEST=/usr/share/games/minetest
 try_path="/usr/share/minetest"
@@ -54,7 +71,7 @@ MT_MYWORLD_NAME=FCAGameAWorld
 MT_MYWORLD_DIR=$HOME/.minetest/worlds/$MT_MYWORLD_NAME
 err_txt=$HOME/err-enliven.txt
 
-
+#endregion paste this part into terminal to get some great environment variables
 
 
 # BACKUP THE WORLD:
@@ -1012,6 +1029,9 @@ fi
 wget https://github.com/minetest-mods/mesecons/archive/master.zip
 mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
 unzip $MTMOD_SRC_ZIP
+if [ -d "$MTMOD_DEST_PATH" ]; then
+  rm -Rf "$MTMOD_DEST_PATH"
+fi
 sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
 if [ ! -d "$MTMOD_DEST_PATH" ]; then
   echo "ERROR: failed to create $MTMOD_DEST_PATH, so cannot continue." > $err_txt
@@ -1345,6 +1365,9 @@ rm -Rvf $MTMOD_UNZ_NAME
 wget https://github.com/Uberi/MineTest-WorldEdit/zipball/master
 mv $MTMOD_DL_ZIP "$MTMOD_SRC_ZIP"
 unzip "$MTMOD_SRC_ZIP"
+if [ -d "$MTMOD_DEST_PATH" ]; then
+  rm -Rf "$MTMOD_DEST_PATH"
+fi
 sudo mv -f $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
 if [ ! -d "$MTMOD_DEST_PATH" ]; then
   echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue." > $err_txt
@@ -1719,6 +1742,7 @@ if [ -f $MTMOD_SRC_ZIP ]; then
   rm -f $MTMOD_SRC_ZIP
 fi
 if [ -d "$MTMOD_DEST_PATH" ]; then
+  # remove old copy, or remove minetest_game's farming
   sudo rm -Rf "$MTMOD_DEST_PATH"
 fi
 wget https://github.com/tenplus1/farming/archive/master.zip
@@ -1888,29 +1912,62 @@ fi
 echo
 echo
 echo
-echo "adding the following necessary integration mods:"
-ls ~/GitHub/EnlivenMinetest/patches/mods-integration/
-sudo cp -R ~/GitHub/EnlivenMinetest/patches/mods-integration/* "$MT_MYGAME_MODS_PATH/"
-echo
-echo "adding the following multiplayer mods:"
-ls ~/GitHub/EnlivenMinetest/patches/mods-multiplayer/
-sudo cp -R ~/GitHub/EnlivenMinetest/patches/mods-multiplayer/* "$MT_MYGAME_MODS_PATH/"
+if [ -d "$PATCHES_PATH" ]; then
+  echo "adding the following necessary integration mods:"
+  ls $PATCHES_PATH/mods-integration/
+  sudo cp -R $PATCHES_PATH/mods-integration/* "$MT_MYGAME_MODS_PATH/"
+  echo
+  echo "adding the following multiplayer mods:"
+  ls $PATCHES_PATH/mods-multiplayer/
+  sudo cp -R $PATCHES_PATH/mods-multiplayer/* "$MT_MYGAME_MODS_PATH/"
+  echo "adding non-manual patches to subgame (vs minetest_game and downloaded mods):"
+  sudo cp -f $PATCHES_PATH/subgame/* "$MT_MYGAME_DIR/"
+  sudo cp -f $PATCHES_PATH/subgame/menu/* "$MT_MYGAME_DIR/menu/"
+  sudo cp -f $PATCHES_PATH/subgame/mods/mobs/textures/* "$MT_MYGAME_DIR/mods/mobs/textures/"
+  sudo cp -f $PATCHES_PATH/subgame/mods/mobs_monster/textures/* "$MT_MYGAME_DIR/mods/mobs_monster/textures/"
+  echo "mods affected: mobs mobs_monsters"
+  PATCHED_FLAG=""
+  BASIS_PATH=$PATCHES_PATH/subgame-basis/mods/bones/init.lua
+  MTMOD_DEST_NAME=bones
+  MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/bones
+  TARGET_PATH=$MTMOD_DEST_PATH/init.lua
+  TRY_DIFF="`diff $BASIS_PATH $TARGET_PATH`"
+  if [ -z "$TRY_DIFF" ]; then
+    sudo cp -f $BASIS_PATH "$MT_MYGAME_DIR/mods/bones/"
+  else
+    echo "FAILED to patch $MTMOD_DEST_NAME since $TARGET_PATH differs from known"
+  fi
+  BASIS_PATH=$PATCHES_PATH/subgame-basis/mods/homedecor_modpack/homedecor/gastronomy.lua
+  TARGET_PATH=$MT_MYGAME_MODS_PATH/homedecor_modpack/homedecor/gastronomy.lua
+  MTMOD_DEST_NAME=homedecor_modpack
+  MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/homedecor_modpack/homedecor
+  TRY_DIFF="`diff $BASIS_PATH $TARGET_PATH`"  
+  if [ -z "$TRY_DIFF" ]; then
+    sudo cp -f $TARGET_PATH "$MTMOD_DEST_PATH/"
+  else
+    echo "FAILED to patch $MTMOD_DEST_NAME since $TARGET_PATH differs from known"
+  fi
+  BASIS_PATH=$PATCHES_PATH/subgame-basis/mods/homedecor_modpack/homedecor/crafts.lua
+  TARGET_PATH=$MT_MYGAME_MODS_PATH/homedecor_modpack/homedecor/crafts.lua
+  MTMOD_DEST_NAME=homedecor_modpack
+  TRY_DIFF="`diff $BASIS_PATH $TARGET_PATH`"  
+  if [ -z "$TRY_DIFF" ]; then
+    sudo cp -f $TARGET_PATH "$MTMOD_DEST_PATH/"
+  else
+    echo "FAILED to patch $MTMOD_DEST_NAME since $TARGET_PATH differs from known"
+  fi
+else
+  echo "did not find $PATCHES_PATH, so skipped automatic patching which is partially implemented"
+fi
 echo
 echo "# remove not available on 0.4.16 stable (is only avail on 0.4.16-dev or higher)"
 echo "sudo rm -Rf /usr/share/games/minetest/games/ENLIVEN/mods/worldedit/worldedit_brush"
 echo "# not recommended:"
-echo "sudo cp -R ~/GitHub/EnlivenMinetest/patches/mods-stopgap/* $MT_MYGAME_MODS_PATH/"
+echo "sudo cp -R $PATCHES_PATH/mods-stopgap/* $MT_MYGAME_MODS_PATH/"
 echo "sudo rm -Rf $MT_MYGAME_MODS_PATH/1.nonworking"
 
-
 echo
 echo
-echo "adding non-manual patches to subgame (vs minetest_game and downloaded mods):"
-sudo cp -f ~/GitHub/EnlivenMinetest/patches/subgame/* "$MT_MYGAME_DIR/"
-sudo cp -f ~/GitHub/EnlivenMinetest/patches/subgame/menu/* "$MT_MYGAME_DIR/menu/"
-sudo cp -f ~/GitHub/EnlivenMinetest/patches/subgame/mods/mobs/textures/* "$MT_MYGAME_DIR/mods/mobs/textures/"
-sudo cp -f ~/GitHub/EnlivenMinetest/patches/subgame/mods/mobs_monster/textures/* "$MT_MYGAME_DIR/mods/mobs_monster/textures/"
-echo "mods affected: mobs"
 echo
 echo "#### $MT_MYWORLD_DIR/world.mt: ####"
 cat "$MT_MYWORLD_DIR/world.mt"
@@ -1937,12 +1994,12 @@ echo "  * for invhack, remember to do: /giveme invhack:tool"
 echo "  * uncomment columns in lapis mod"
 echo "  * Make sure client (server done already above) minetest.conf has secure.trusted_mods = advanced_npc"
 echo "  * Make sure writable minetest conf was successfully written"
-echo "    over /usr/local/share/minetest/games/enliven/minetest.conf with:"
+echo "    over $MT_MYGAME_DIR/minetest.conf with (NOTE: protector_drop is deprecated):"
 echo "protector_radius = 7"
 echo "protector_pvp = true"
 echo "protector_pvp_spawn = 10"
-echo "protector_drop = true"
-echo "protector_hurt = 1"
+echo "protector_drop = false"
+echo "protector_hurt = 3"
 echo ""
 echo "default_privs = interact,shout,home"
 echo "max_users = 50"
