mock_tnt now causes damage but only to players and mobs
(and causes playereffects if playereffects is installed).  Also,
switched from monoidal_effects to player_monoids and playereffects.
Author of monoidal_effects says it is deprecated by player_monoids and
that functionality stripped out is present in playereffects.

diff --git a/etc/change_world_name_manually_first/game-install-ENLIVEN b/etc/change_world_name_manually_first/game-install-ENLIVEN
--- a/etc/change_world_name_manually_first/game-install-ENLIVEN
+++ b/etc/change_world_name_manually_first/game-install-ENLIVEN
@@ -1174,27 +1174,61 @@ if [ ! -d "$MTMOD_DEST_PATH" ]; then
 fi
 
 
-#if [ -f playereffects_Wuzzy.zip ]; then
-#  rm playereffects_Wuzzy.zip
-#fi
-#if [ -f "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip" ]; then
-#  rm "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip"
-#fi
-#if [ -d "minetest_playereffects-3b860c7" ]; then
-#  rm -Rf minetest_playereffects-3b860c7
-#fi
-#cd "$HOME/Downloads"
+MTMOD_DEST_NAME=playereffects
+MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
+if [ -f playereffects_Wuzzy.zip ]; then
+  rm playereffects_Wuzzy.zip
+fi
+if [ -f "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip" ]; then
+  rm "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip"
+fi
+if [ -d "minetest_playereffects-3b860c7" ]; then
+  rm -Rf minetest_playereffects-3b860c7
+fi
+if [ -d "minetest_playereffects" ]; then
+  rm -Rf minetest_playereffects
+fi
+cd "$HOME/Downloads"
+git clone http://repo.or.cz/minetest_playereffects.git
 #wget http://repo.or.cz/minetest_playereffects.git/snapshot/3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip
 #mv "3b860c74ae9803f9a979b12c6f6beb74f96ae62c.zip" playereffects_Wuzzy.zip
 #unzip playereffects_Wuzzy.zip
 #sudo mv minetest_playereffects* "$MT_MYGAME_MODS_PATH/playereffects"
+sudo mv minetest_playereffects "$MTMOD_DEST_PATH"
 
 #Byakuren. <https://forum.minetest.net/viewtopic.php?f=9&t=13941>.
 
+#monoidal_effects by Byakuren [raymoo on GitHub] is deprecated by player_monoids by Byakuren [raymoo on GitHub] +playereffects by Wuzzy
+#according to the author https://forum.minetest.net/viewtopic.php?t=13941
+#cd $HOME\Downloads
+#MTMOD_DL_ZIP=master.zip
+#MTMOD_SRC_ZIP=monoidal_effects.zip
+#MTMOD_UNZ_NAME=monoidal_effects-master
+#MTMOD_DEST_NAME=monoidal_effects
+#MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
+##if [ -d "$MTMOD_UNZ_NAME" ]; then
+#rm -Rf $MTMOD_UNZ_NAME
+##fi
+#if [ -f $MTMOD_DL_ZIP ]; then
+#  rm -f $MTMOD_DL_ZIP
+#fi
+#if [ -f $MTMOD_SRC_ZIP ]; then
+#  rm $MTMOD_SRC_ZIP
+#fi
+#wget https://github.com/minetest-mods/monoidal_effects/archive/master.zip
+#mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
+#unzip $MTMOD_SRC_ZIP
+#sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
+#if [ ! -d "$MTMOD_DEST_PATH" ]; then
+#  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue."
+#  exit 1  
+#fi
+
+cd $HOME\Downloads
 MTMOD_DL_ZIP=master.zip
-MTMOD_SRC_ZIP=monoidal_effects.zip
-MTMOD_UNZ_NAME=monoidal_effects-master
-MTMOD_DEST_NAME=monoidal_effects
+MTMOD_SRC_ZIP=player_monoids.zip
+MTMOD_UNZ_NAME=player_monoids-master
+MTMOD_DEST_NAME=player_monoids
 MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
 #if [ -d "$MTMOD_UNZ_NAME" ]; then
 rm -Rf $MTMOD_UNZ_NAME
@@ -1205,7 +1239,7 @@ fi
 if [ -f $MTMOD_SRC_ZIP ]; then
   rm $MTMOD_SRC_ZIP
 fi
-wget https://github.com/minetest-mods/monoidal_effects/archive/master.zip
+wget https://github.com/minetest-mods/player_monoids/archive/master.zip
 mv $MTMOD_DL_ZIP $MTMOD_SRC_ZIP
 unzip $MTMOD_SRC_ZIP
 sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
@@ -1213,6 +1247,7 @@ if [ ! -d "$MTMOD_DEST_PATH" ]; then
   echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue."
   exit 1  
 fi
+
 
 cd "$HOME/Downloads"
 MTMOD_DL_ZIP=master
