changed to hudbars, added scripts to free up storage

diff --git a/etc/change_world_name_manually_first/game-install-ENLIVEN b/etc/change_world_name_manually_first/game-install-ENLIVEN
--- a/etc/change_world_name_manually_first/game-install-ENLIVEN
+++ b/etc/change_world_name_manually_first/game-install-ENLIVEN
@@ -225,7 +225,7 @@ echo "motd = \"Actions and chat messages are logged. Use inventory to see recipe
 echo "disallow_empty_passwords = true" >> "$WRITEABLE_MINETEST_CONF"
 echo "secure.trusted_mods = advanced_npc" >> "$WRITEABLE_MINETEST_CONF"
 echo "server_dedicated = false" >> "$WRITEABLE_MINETEST_CONF"
-
+echo "hudbars_bar_type = statbar_modern" >> "$WRITEABLE_MINETEST_CONF"
 sudo mv -f $HOME/minetest.conf "$USR_SHARE_MINETEST/games/$MT_MYGAME_NAME/minetest.conf"
 echo "load_mod_protector = true" >> $MT_MYWORLD_DIR/world.mt
 
@@ -497,6 +497,35 @@ wget https://github.com/MinetestForFun/server-minetestforfun/raw/master/mods/trm
 wget https://github.com/MinetestForFun/server-minetestforfun/raw/master/mods/trm_pyramids/init.lua
 wget https://github.com/MinetestForFun/server-minetestforfun/raw/master/mods/trm_pyramids/more_trms.lua
 
+#Wuzzy's hudbars (no builtin bars; used by sprint, hbhunger, and hbarmor) https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=hunger
+cd $HOME/Downloads
+#MTMOD_DL_ZIP=master.zip
+#MTMOD_SRC_ZIP=hudbars.zip
+MTMOD_UNZ_NAME=minetest_hudbars
+MTMOD_DEST_NAME=hudbars
+MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
+#if [ -d "$MTMOD_UNZ_NAME" ]; then
+rm -Rf $MTMOD_UNZ_NAME
+#fi
+#if [ -f $MTMOD_DL_ZIP ]; then
+#  rm -f $MTMOD_DL_ZIP
+#fi
+#if [ -f $MTMOD_SRC_ZIP ]; then
+#  rm -f $MTMOD_SRC_ZIP
+#fi
+if [ -d "$MTMOD_DEST_PATH" ]; then
+  sudo rm -Rf "$MTMOD_DEST_PATH"
+fi
+git clone git://repo.or.cz/minetest_hudbars.git
+#aka http://repo.or.cz/w/minetest_hudbars.git
+sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
+if [ ! -d "$MTMOD_DEST_PATH" ]; then
+  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue."
+  exit 1  
+fi
+
+
+if [ ! -d "$MT_MYGAME_MODS_PATH/hudbars" ]; then
 cd "$HOME/Downloads"
 #MTMOD_DL_ZIP=hud_hunger-2_x_1-BlockMen.zip
 #MTMOD_SRC_ZIP=hud_hunger-2_x_1-BlockMen.zip
@@ -526,6 +555,72 @@ rm -Rvf $MTMOD_UNZ_NAME
 #tenplus1's fixes nil air, nil player, and sprint
 wget https://github.com/tenplus1/hud_hunger/archive/master.zip
 unzip $MTMOD_SRC_ZIP
+sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
+sudo rm "$MTMOD_DEST_PATH/hunger/functions_UNUSED_sprint.lua"
+sudo mv "$MTMOD_DEST_PATH/hunger/functions.lua" "$MTMOD_DEST_PATH/hunger/functions_UNUSED_sprint.lua"
+sudo mv "$MTMOD_DEST_PATH/hunger/functions_(nosprint).lua" "$MTMOD_DEST_PATH/hunger/functions.lua"
+sudo rm "$MTMOD_DEST_PATH/hunger/init_UNUSED_sprint.lua"
+sudo mv "$MTMOD_DEST_PATH/hunger/init.lua" "$MTMOD_DEST_PATH/hunger/init_UNUSED_sprint.lua"
+sudo mv "$MTMOD_DEST_PATH/hunger/init_(nosprint).lua" "$MTMOD_DEST_PATH/hunger/init.lua"
+if [ ! -d "$MTMOD_DEST_PATH" ]; then
+  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue."
+  exit 1  
+fi
+# END IF no hudbars mod
+else
+if [ -d "$MT_MYGAME_MODS_PATH/hud_hunger" ]; then
+sudo rm -Rvf "$MT_MYGAME_MODS_PATH/hud_hunger"
+fi
+fi
+
+#Wuzzy's hbarmor for hudbars https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=hunger
+cd $HOME/Downloads
+#MTMOD_DL_ZIP=master.zip
+#MTMOD_SRC_ZIP=hudbars.zip
+MTMOD_UNZ_NAME=minetest_hbarmor
+MTMOD_DEST_NAME=hbarmor
+MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
+#if [ -d "$MTMOD_UNZ_NAME" ]; then
+rm -Rf $MTMOD_UNZ_NAME
+#fi
+#if [ -f $MTMOD_DL_ZIP ]; then
+#  rm -f $MTMOD_DL_ZIP
+#fi
+#if [ -f $MTMOD_SRC_ZIP ]; then
+#  rm -f $MTMOD_SRC_ZIP
+#fi
+if [ -d "$MTMOD_DEST_PATH" ]; then
+  sudo rm -Rf "$MTMOD_DEST_PATH"
+fi
+git clone git://repo.or.cz/minetest_hbarmor.git
+#aka http://repo.or.cz/minetest_hbarmor.git/snapshot/bfc5f8cbb560eff6f206eec3242f8401d11c1310.zip
+sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
+if [ ! -d "$MTMOD_DEST_PATH" ]; then
+  echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue."
+  exit 1  
+fi
+
+#Wuzzy's hbhunger for hudbars https://forum.minetest.net/viewtopic.php?f=11&t=11153&hilit=hunger
+cd $HOME/Downloads
+#MTMOD_DL_ZIP=master.zip
+#MTMOD_SRC_ZIP=hbhunger.zip
+MTMOD_UNZ_NAME=minetest_hbhunger
+MTMOD_DEST_NAME=hbhunger
+MTMOD_DEST_PATH=$MT_MYGAME_MODS_PATH/$MTMOD_DEST_NAME
+#if [ -d "$MTMOD_UNZ_NAME" ]; then
+rm -Rf $MTMOD_UNZ_NAME
+#fi
+#if [ -f $MTMOD_DL_ZIP ]; then
+#  rm -f $MTMOD_DL_ZIP
+#fi
+#if [ -f $MTMOD_SRC_ZIP ]; then
+#  rm -f $MTMOD_SRC_ZIP
+#fi
+if [ -d "$MTMOD_DEST_PATH" ]; then
+  sudo rm -Rf "$MTMOD_DEST_PATH"
+fi
+git clone git://repo.or.cz/minetest_hbhunger.git
+#aka http://repo.or.cz/minetest_hbhunger.git/snapshot/da70eba4fd0a9644cdb0a5b0d7ee3d93f7e61acf.zip
 sudo mv $MTMOD_UNZ_NAME "$MTMOD_DEST_PATH"
 if [ ! -d "$MTMOD_DEST_PATH" ]; then
   echo "ERROR: failed to unzip $MTMOD_DEST_PATH, so cannot continue."
